  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
  labels:
    app: restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi 
    spec:
      containers:
      - name: nodeserver
        image: rafdev0904/ecommerce:71
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: restapi-service
spec:
  selector:
    app: restapi
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
    nodePort: 31110
